# SPDX-FileCopyrightText: Copyright (C) 2025 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: Apache-2.0

name: Install Dependencies
description: Install the dependencies needed by the app, using npm

runs:
  using: "composite"
  steps:
      # Install dependencies
      # Use setup-node's built-in functionality for caching and restoring npm dependencies
      # See: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows
      - uses: actions/setup-node@v6.0.0
        with:
          # renovate: datasource=node-version dependency=node
          node-version: 22.21.1
          cache: 'npm'
      - name: Check npm installation
        run: npm -v
        shell: bash
      - name: Install dependencies
        run: npm ci
        shell: bash
