name: Build App Setup
description: Setup before building the app

inputs:
  NPMRC_FILE:
    description: 'Secret with the contents of .npmrc'
    required: true
  ENV_CONFIG_JS:
    description: 'Contents of the file `opal.config.js` for the given environment'
    required: true
  ENV_GOOGLE_SERVICES:
    description: 'Contents of the file `google-services.json` for the given environment'
    required: true

runs:
  using: "composite"
  steps:
    # Install dependencies
    - name: Check npm installation
      run: npm -v
      shell: bash
    - name: Load .npmrc
      run: echo "${NPMRC_FILE}" > .npmrc
      shell: bash
    - name: Install dependencies
      run: npm ci --cache .npm --prefer-offline
      shell: bash

    # Initialize the environment files needed to build the app from repository-level Actions variables
    - name: Load environment files
      run: |
        mkdir env/$ENVIRONMENT
        echo "${ENV_CONFIG_JS}" > env/$ENVIRONMENT/opal.config.js
        echo "${ENV_GOOGLE_SERVICES}" > env/$ENVIRONMENT/google-services.json
      shell: bash
