name: Build App Setup
description: Setup before building the app

runs:
  using: "composite"
  steps:
    # Select the environment
    - run: echo $ENVIRONMENT | tr '[a-z]' '[A-Z]'
    - name: Convert environment to all caps
      run: echo "ENVIRONMENT_CAPS=$(echo $ENVIRONMENT | tr '[a-z]' '[A-Z]')" >> $GITHUB_ENV
    - name: Print environment
      run: |
        echo "Environment: $ENVIRONMENT ($ENVIRONMENT_CAPS)"

    # Install dependencies
    - name: Check npm installation
      run: npm -v
    - name: Load .npmrc
      run: echo "${NPMRC_FILE}" > .npmrc
      env:
        NPMRC_FILE: ${{ secrets.NPMRC_FILE }}
    - name: Install dependencies
      run: npm ci --cache .npm --prefer-offline

    # Initialize the environment files needed to build the app from repository-level Actions variables
    - name: Load environment files
      run: |
        mkdir env/$ENVIRONMENT
        echo "${ENV_CONFIG_JS}" > env/$ENVIRONMENT/opal.config.js
        echo "${ENV_GOOGLE_SERVICES}" > env/$ENVIRONMENT/google-services.json
      env:
        ENV_CONFIG_JS: ${{ vars[format('{0}_CONFIG_JS', env.ENVIRONMENT_CAPS)] }}
        ENV_GOOGLE_SERVICES: ${{ vars[format('{0}_GOOGLE_SERVICES', env.ENVIRONMENT_CAPS)] }}
