# SPDX-FileCopyrightText: Copyright 2025 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: Apache-2.0

# TODO
# This workflow is explained in __________; please keep that documentation file up to date when making changes here.

name: Build App
# Default to dev when running automatically (see also "env" below)
run-name: Building the app for ${{ inputs.ENVIRONMENT || 'dev' }} 📦
on:
  # When pushing to main, automatically build for dev
  push:
    branches:
      # TODO testing
#      - main
      - SB.github-actions

  # Offer a manual interface to build for all other environments as needed
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: 'Environment in which to build'
        type: choice
        required: true
        default: 'dev'
        options:
          - dev
          - prod

# Read the target environment from workflow_dispatch inputs, or default to dev
env:
  ENVIRONMENT: ${{ inputs.ENVIRONMENT || 'dev' }}

jobs:
  build:
    runs-on: macos-latest
    steps:
      # Setup
      - run: echo $ENVIRONMENT | tr '[a-z]' '[A-Z]'
      - name: Convert environment to all caps
        run: echo "ENVIRONMENT_CAPS=$(echo $ENVIRONMENT | tr '[a-z]' '[A-Z]')" >> $GITHUB_ENV
      - name: Print environment
        run: |
          echo "Environment: $ENVIRONMENT ($ENVIRONMENT_CAPS)"
      - uses: actions/checkout@v4
      - name: Check npm installation
        run: npm -v
      - name: Load .npmrc
        run: echo "${NPMRC}" > .npmrc
        env:
          NPMRC: ${{ secrets.NPMRC }}
      - name: Install dependencies
        run: npm ci --cache .npm --prefer-offline
      # Get the environment files needed to build the app from repository-level Actions variables
      - name: Load environment files
        run: |
          mkdir env/$ENVIRONMENT
          echo "${ENV_CONFIG_JS}" > env/$ENVIRONMENT/opal.config.js
          echo "${ENV_GOOGLE_SERVICES}" > env/$ENVIRONMENT/google-services.json
        env:
          ENV_CONFIG_JS: ${{ vars[format('{0}_CONFIG_JS', env.ENVIRONMENT_CAPS)] }}
          ENV_GOOGLE_SERVICES: ${{ vars[format('{0}_GOOGLE_SERVICES', env.ENVIRONMENT_CAPS)] }}

      # Build the app
      - name: Build the app
        run: npm run build:app:ios:device:ci --env=$ENVIRONMENT
