# SPDX-FileCopyrightText: Copyright 2025 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>
#
# SPDX-License-Identifier: Apache-2.0

# TODO
# This workflow is explained in `docs/deployment/ci-cd.md`; please keep that documentation file up to date when making changes here.

name: Deploy Web
run-name: Deploying the web app for ${{ inputs.ENVIRONMENT }} 🚀
on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string

permissions:
  contents: read

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Download web build artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: Web app
          run-id: ${{ github.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: sudo apt-get install lftp
      - run: lftp --version
      - run: echo "Listing web build directory..."
      - run: ls -la www
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false

      # Upload web files
      # lftp mirror arguments: https://www.cyberciti.biz/faq/lftp-mirror-example/
      - run: >
          lftp -e "
            set cmd:fail-exit yes;
            open $FTP_HOST;
            user $FTP_USER $FTP_PASSWORD;
            mirror --exclude='app' --exclude='content' --reverse --delete --verbose ./static/landingpage/ ./app/${ENVIRONMENT}/;
            mirror --reverse --delete --use-pget-n=10 --verbose ./www/ ./app/${ENVIRONMENT}/app/;
            ls -la app/${ENVIRONMENT};
            bye
          "
        env:
          ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
          FTP_HOST: ${{ vars.FTP_HOST }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_USER: ${{ vars.FTP_USER }}
